/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ritesh.crm;

import java.sql.*;
import javax.swing.JOptionPane;
import static ritesh.crm.Main.session_user;

/**
 *
 * @author Trainee
 */
public class AdminJframe extends javax.swing.JFrame {

    
    public AdminJframe() {
        initComponents();
        jLabel1.setText("Hello "+session_user+", Welcome to the DashBoard !!");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        add_new_users_btn = new javax.swing.JButton();
        view_all_users_btn = new javax.swing.JButton();
        view_sales_btn = new javax.swing.JButton();
        check_av_products_btn = new javax.swing.JButton();
        view_all_customers_btn = new javax.swing.JButton();
        inventry_btn = new javax.swing.JButton();
        invoice_btn = new javax.swing.JButton();
        check_order_details_btn = new javax.swing.JButton();
        duplicate_bill_btn = new javax.swing.JButton();
        logout_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin DashBoard");

        add_new_users_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        add_new_users_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ritesh/icons/insert_object.png"))); // NOI18N
        add_new_users_btn.setText("Add New Users");
        add_new_users_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_new_users_btnActionPerformed(evt);
            }
        });

        view_all_users_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        view_all_users_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ritesh/icons/user.png"))); // NOI18N
        view_all_users_btn.setText("View All Users");
        view_all_users_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_all_users_btnActionPerformed(evt);
            }
        });

        view_sales_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        view_sales_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ritesh/icons/system_software_update.png"))); // NOI18N
        view_sales_btn.setText("View Sales");
        view_sales_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_sales_btnActionPerformed(evt);
            }
        });

        check_av_products_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        check_av_products_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ritesh/icons/symbol_check.png"))); // NOI18N
        check_av_products_btn.setText("Check Available Products");
        check_av_products_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_av_products_btnActionPerformed(evt);
            }
        });

        view_all_customers_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        view_all_customers_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ritesh/icons/symbol_check.png"))); // NOI18N
        view_all_customers_btn.setText("View All Customers");
        view_all_customers_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_all_customers_btnActionPerformed(evt);
            }
        });

        inventry_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        inventry_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ritesh/icons/insert_object.png"))); // NOI18N
        inventry_btn.setText("Inventry");
        inventry_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventry_btnActionPerformed(evt);
            }
        });

        invoice_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        invoice_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ritesh/icons/symbol_check.png"))); // NOI18N
        invoice_btn.setText("Generate Invoice");
        invoice_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invoice_btnActionPerformed(evt);
            }
        });

        check_order_details_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        check_order_details_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ritesh/icons/symbol_check.png"))); // NOI18N
        check_order_details_btn.setText("Check Order Details");
        check_order_details_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_order_details_btnActionPerformed(evt);
            }
        });

        duplicate_bill_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        duplicate_bill_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ritesh/icons/system_software_update.png"))); // NOI18N
        duplicate_bill_btn.setText("Duplicate Bill");
        duplicate_bill_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duplicate_bill_btnActionPerformed(evt);
            }
        });

        logout_btn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        logout_btn.setForeground(new java.awt.Color(204, 0, 0));
        logout_btn.setText("Log-Out");
        logout_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_btnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 153));
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(482, 482, 482)
                        .addComponent(logout_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(invoice_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(check_av_products_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(add_new_users_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(check_order_details_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                            .addComponent(view_all_users_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(view_all_customers_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(duplicate_bill_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                            .addComponent(inventry_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(view_sales_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logout_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(add_new_users_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(view_all_users_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(view_sales_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(check_av_products_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(view_all_customers_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(inventry_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(invoice_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                    .addComponent(check_order_details_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(duplicate_bill_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void add_new_users_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_new_users_btnActionPerformed
        
        AddnewuserJframe adnew = new AddnewuserJframe();
        adnew.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_add_new_users_btnActionPerformed

    private void check_av_products_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_av_products_btnActionPerformed
        
        ProductsJframe pdj = new ProductsJframe();
        pdj.setVisible(true);
    }//GEN-LAST:event_check_av_products_btnActionPerformed

    private void view_all_customers_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_all_customers_btnActionPerformed
        
        CustomersJframe csjf = new CustomersJframe();
        csjf.setVisible(true);
    }//GEN-LAST:event_view_all_customers_btnActionPerformed

    private void inventry_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventry_btnActionPerformed
        
        ProductUpdateJframe pdjf = new ProductUpdateJframe();
        pdjf.setVisible(true);
    }//GEN-LAST:event_inventry_btnActionPerformed

    private void invoice_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invoice_btnActionPerformed
        
        TryingTable ttjf = new TryingTable();
        ttjf.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_invoice_btnActionPerformed

    private void logout_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_btnActionPerformed
        
        AdminloginJframe bylogout = new AdminloginJframe();
        bylogout.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_logout_btnActionPerformed

    private void view_all_users_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_all_users_btnActionPerformed
        
        usersJframe usj = new usersJframe();
        usj.setVisible(true);
    }//GEN-LAST:event_view_all_users_btnActionPerformed

    private void check_order_details_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_order_details_btnActionPerformed

        String order_id = JOptionPane.showInputDialog("Enter the Order Id :");
            if(order_id!=null){
                try(Connection con = new DBConnection().getConnection()){
                    Statement st = con.createStatement();
                    ResultSet rs = st.executeQuery("Select * from orders Where order_id='"+order_id+"'");
                    if(rs.next()){
                        OrderDetails show_od_details = new OrderDetails();
                        show_od_details.show_order_details(order_id);
                        show_od_details.setVisible(true);
                    }else{
                        JOptionPane.showMessageDialog(null,"No such Order EXIST, Please Try again with a valid Order ID","ERROR",JOptionPane.ERROR_MESSAGE);
                }
                }catch(Exception e){
                    System.err.println(e);
                }
            }
    }//GEN-LAST:event_check_order_details_btnActionPerformed

    private void view_sales_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_sales_btnActionPerformed
        
        new Sales().setVisible(true);
    }//GEN-LAST:event_view_sales_btnActionPerformed

    private void duplicate_bill_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duplicate_bill_btnActionPerformed
        String dup_order_id = JOptionPane.showInputDialog("Enter the Order Id");
        try(Connection con = new DBConnection().getConnection()){
            Statement st = con.createStatement();
            ResultSet rs=st.executeQuery("SELECT * FROM orders WHERE order_id='"+dup_order_id+"'");
            if(rs.next()){
                Invoice dup_invoice=new Invoice(dup_order_id);
                dup_invoice.setVisible(true);
                
            }else
                JOptionPane.showMessageDialog(null, "No Such Order exists!! Please try again with a correct Order ID !! ", "Alert", JOptionPane.ERROR_MESSAGE);
        }catch(Exception e){
            System.err.println(e);
        }
    }//GEN-LAST:event_duplicate_bill_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminJframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_new_users_btn;
    private javax.swing.JButton check_av_products_btn;
    private javax.swing.JButton check_order_details_btn;
    private javax.swing.JButton duplicate_bill_btn;
    private javax.swing.JButton inventry_btn;
    private javax.swing.JButton invoice_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton logout_btn;
    private javax.swing.JButton view_all_customers_btn;
    private javax.swing.JButton view_all_users_btn;
    private javax.swing.JButton view_sales_btn;
    // End of variables declaration//GEN-END:variables
}
