/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ritesh.crm;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static ritesh.crm.Main.session_user;


/**
 *
 * @author RITESH KUMAR SINGH
 */
public class DashBoard extends javax.swing.JFrame {

    /**
     * Creates new form DashBoard
     */
    
    public DashBoard() {
        
        initComponents();
        jLabel1.setText("Hello "+session_user+", Welcome to the DashBoard !!");
        jLabel2.setText("Hey "+session_user+", Your today Sales are :");
        update_users_sales_table();
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        customers_btn = new javax.swing.JButton();
        check_product_details_btn = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        check_order_details_btn = new javax.swing.JButton();
        Generate_Invoice_btn1 = new javax.swing.JButton();
        sales_records_btn = new javax.swing.JButton();
        log_out_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        refresh_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DashBoard");
        setPreferredSize(new java.awt.Dimension(1167, 740));

        customers_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        customers_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ritesh/icons/user.png"))); // NOI18N
        customers_btn.setText("Customers");
        customers_btn.setMaximumSize(new java.awt.Dimension(165, 57));
        customers_btn.setMinimumSize(new java.awt.Dimension(165, 57));
        customers_btn.setPreferredSize(new java.awt.Dimension(165, 57));
        customers_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customers_btnActionPerformed(evt);
            }
        });

        check_product_details_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        check_product_details_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ritesh/icons/download.png"))); // NOI18N
        check_product_details_btn.setText("Check Products Details");
        check_product_details_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_product_details_btnActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ritesh/icons/insert_object.png"))); // NOI18N
        jButton3.setText("Add/Update Products");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        check_order_details_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        check_order_details_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ritesh/icons/symbol_check.png"))); // NOI18N
        check_order_details_btn.setText("Check Order Details");
        check_order_details_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_order_details_btnActionPerformed(evt);
            }
        });

        Generate_Invoice_btn1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Generate_Invoice_btn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ritesh/icons/download.png"))); // NOI18N
        Generate_Invoice_btn1.setText("New Order");
        Generate_Invoice_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Generate_Invoice_btn1ActionPerformed(evt);
            }
        });

        sales_records_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        sales_records_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ritesh/icons/symbol_check.png"))); // NOI18N
        sales_records_btn.setText("Sales Records");
        sales_records_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sales_records_btnActionPerformed(evt);
            }
        });

        log_out_btn.setBackground(new java.awt.Color(255, 255, 255));
        log_out_btn.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        log_out_btn.setForeground(new java.awt.Color(255, 0, 51));
        log_out_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ritesh/icons/logout.png"))); // NOI18N
        log_out_btn.setText("Log Out");
        log_out_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                log_out_btnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 153));
        jLabel1.setText("Welcome");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 204));
        jLabel2.setText("jLabel2");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order Id", "Customer Id", "Amount", "Time"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
        }

        refresh_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ritesh/icons/refresh.png"))); // NOI18N
        refresh_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refresh_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(refresh_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(refresh_btn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(check_product_details_btn)
                                    .addComponent(Generate_Invoice_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(check_order_details_btn)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(sales_records_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                                .addComponent(customers_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(24, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(log_out_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(log_out_btn)
                        .addGap(23, 23, 23)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(check_product_details_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(check_order_details_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Generate_Invoice_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sales_records_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(customers_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void update_users_sales_table(){
        DefaultTableModel model = new DefaultTableModel(new String[]{"Order Id","Customer Id","Amount","Time"},0);
        long milis = System.currentTimeMillis();
        java.sql.Date date = new java.sql.Date(milis);
        String dt = date.toString();
        try(Connection con = new DBConnection().getConnection()){
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM orders WHERE sold_by ='"+session_user+"' and date='"+dt+"'");
            while(rs.next()){
                model.addRow(new Object[]{rs.getString("order_id"),rs.getString("customer_id"),rs.getString("amount"),rs.getString("time")});
            }
        }catch(Exception e){
            System.err.println(e);
        }
        jTable1.setModel(model);
    }
    
    private void check_order_details_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_order_details_btnActionPerformed
        
            String order_id = JOptionPane.showInputDialog("Enter the Order Id :");
            if(order_id!=null){
                try(Connection con = new DBConnection().getConnection()){
                    Statement st = con.createStatement();
                    ResultSet rs = st.executeQuery("Select * from orders Where order_id='"+order_id+"'");
                    if(rs.next()){
                        OrderDetails show_od_details = new OrderDetails();
                        show_od_details.show_order_details(order_id);
                        show_od_details.setVisible(true);
                    }else{
                        JOptionPane.showMessageDialog(null,"No such Order EXIST, Please Try again with a valid Order ID","ERROR",JOptionPane.ERROR_MESSAGE);
                }
                }catch(Exception e){
                    System.err.println(e);
                }
            }
            
        
    }//GEN-LAST:event_check_order_details_btnActionPerformed

    private void check_product_details_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_product_details_btnActionPerformed
        
        ProductsJframe pd_obj = new ProductsJframe();
        pd_obj.setVisible(true);
    }//GEN-LAST:event_check_product_details_btnActionPerformed

    private void customers_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customers_btnActionPerformed
        
        CustomersJframe cust_obj = new CustomersJframe();
        cust_obj.setVisible(true);
    }//GEN-LAST:event_customers_btnActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        ProductUpdateJframe product_update=new ProductUpdateJframe();
        product_update.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void Generate_Invoice_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Generate_Invoice_btn1ActionPerformed
        
        TryingTable tb= new TryingTable();
        tb.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Generate_Invoice_btn1ActionPerformed

    private void sales_records_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sales_records_btnActionPerformed
        
        new Sales().setVisible(true);
    }//GEN-LAST:event_sales_records_btnActionPerformed

    private void log_out_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_log_out_btnActionPerformed
        
        MainJframe mj= new MainJframe();
        mj.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_log_out_btnActionPerformed

    private void refresh_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refresh_btnActionPerformed
       
        update_users_sales_table();
    }//GEN-LAST:event_refresh_btnActionPerformed
   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Generate_Invoice_btn1;
    private javax.swing.JButton check_order_details_btn;
    private javax.swing.JButton check_product_details_btn;
    private javax.swing.JButton customers_btn;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton log_out_btn;
    private javax.swing.JButton refresh_btn;
    private javax.swing.JButton sales_records_btn;
    // End of variables declaration//GEN-END:variables
}
