/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ritesh.crm;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;



/**
 *
 * @author Trainee
 */
public class ProductUpdateJframe extends javax.swing.JFrame {

    /**
     * Creates new form ProductUpdateJframe
     */
    public ProductUpdateJframe() {
        initComponents();
    }
       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        product_name_label = new javax.swing.JLabel();
        product_id_label = new javax.swing.JLabel();
        price_label = new javax.swing.JLabel();
        quantity_label = new javax.swing.JLabel();
        product_name_tfield = new javax.swing.JTextField();
        product_id_tfield = new javax.swing.JTextField();
        quantity_tfield = new javax.swing.JTextField();
        price_tfield = new javax.swing.JTextField();
        update_quantity_btn = new javax.swing.JButton();
        add_new_product_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setTitle("Product Update");

        product_name_label.setText("Product Name :");

        product_id_label.setText("Product Id       :");

        price_label.setText("Price                :");

        quantity_label.setText("Quantity          :");

        update_quantity_btn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        update_quantity_btn.setForeground(new java.awt.Color(0, 153, 51));
        update_quantity_btn.setText("Update Quantity");
        update_quantity_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_quantity_btnActionPerformed(evt);
            }
        });

        add_new_product_btn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        add_new_product_btn.setForeground(new java.awt.Color(0, 153, 0));
        add_new_product_btn.setText("Add New Product");
        add_new_product_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_new_product_btnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Product Update");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(price_label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(product_id_label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(product_name_label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(quantity_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(product_name_tfield, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                                .addComponent(product_id_tfield)
                                .addComponent(price_tfield)
                                .addComponent(quantity_tfield))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(update_quantity_btn)
                                .addGap(5, 5, 5)
                                .addComponent(add_new_product_btn))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(product_name_tfield, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(product_name_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(product_id_label, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(product_id_tfield))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(price_label, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(price_tfield))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(quantity_label, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(quantity_tfield))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(update_quantity_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add_new_product_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    //private String product_name = new String();
    private void add_new_product_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_new_product_btnActionPerformed
        
        final String product_name=product_name_tfield.getText();
        final String product_id=product_id_tfield.getText();
        final String price=price_tfield.getText();
        final String quantity=quantity_tfield.getText();
        
        try(Connection con = new DBConnection().getConnection()){
            Statement stmt = con.createStatement();
            stmt.executeUpdate("INSERT INTO products VALUES(NULL,NULL,'"+product_name+"','"+price+"','"+quantity+"')");
            JOptionPane.showMessageDialog(null,"Data Updated Successfully !");
            con.close();
        }catch(Exception e){
            System.err.println(e);
        }
        
    }//GEN-LAST:event_add_new_product_btnActionPerformed

    private void update_quantity_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_quantity_btnActionPerformed
        
        final String product_name=product_name_tfield.getText();
        final String product_id=product_id_tfield.getText();
        final String price=price_tfield.getText();
        final String quantity=quantity_tfield.getText();
        int new_qty=0;
        try(Connection con = new DBConnection().getConnection()){
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("SELECT quantity FROM products WHERE product_id='"+product_id+"' and product_name='"+product_name+"'");
            if(rs.next()){
                new_qty=rs.getInt("quantity")+Integer.parseInt(quantity);
            }
            Statement stmt = con.createStatement();
            stmt.executeUpdate("UPDATE products SET quantity='"+new_qty+"' WHERE product_id='"+product_id+"' and product_name='"+product_name+"'");
            
            JOptionPane.showMessageDialog(null,"Product Quantity Updated Successfully !");
            con.close();
        }catch(Exception e){
            System.err.println(e);
        }
        
    }//GEN-LAST:event_update_quantity_btnActionPerformed
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductUpdateJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductUpdateJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductUpdateJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductUpdateJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductUpdateJframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_new_product_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel price_label;
    private javax.swing.JTextField price_tfield;
    private javax.swing.JLabel product_id_label;
    private javax.swing.JTextField product_id_tfield;
    private javax.swing.JLabel product_name_label;
    private javax.swing.JTextField product_name_tfield;
    private javax.swing.JLabel quantity_label;
    private javax.swing.JTextField quantity_tfield;
    private javax.swing.JButton update_quantity_btn;
    // End of variables declaration//GEN-END:variables
}
