/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ritesh.crm;

import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import static ritesh.crm.Main.user_role;



/**
 *
 * @author RITESH KUMAR SINGH
 */
public class TryingTable extends javax.swing.JFrame {

    /**
     * Creates new form TryingTable
     */
    public TryingTable() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        add_jpanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        product_name_tfield = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        product_id_tfield = new javax.swing.JTextField();
        price_jlabel = new javax.swing.JLabel();
        price_tfield = new javax.swing.JTextField();
        quantity_left_jlabel = new javax.swing.JLabel();
        quantity_left_tfield = new javax.swing.JTextField();
        quantity_jlabel = new javax.swing.JLabel();
        quantity_tfield = new javax.swing.JTextField();
        Add_product_btn = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        proceed_btn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        customer_name_label = new javax.swing.JLabel();
        customers_name_tfield = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        mobile_tfield = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        email_tfield = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        back_to_dashboard_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Generate Invoice");
        setLocation(new java.awt.Point(200, 0));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Name", "Product Id", "Price", "Quantity", "Amount", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(450);
            jTable1.getColumnModel().getColumn(5).setMinWidth(60);
            jTable1.getColumnModel().getColumn(5).setPreferredWidth(60);
            jTable1.getColumnModel().getColumn(5).setMaxWidth(60);
        }

        jLabel2.setText("Search product here :");

        product_name_tfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                product_name_tfieldKeyReleased(evt);
            }
        });

        jLabel1.setText("product_id");

        price_jlabel.setText("Price");

        quantity_left_jlabel.setText("Quantity  left");

        quantity_jlabel.setText("Quantity");

        Add_product_btn.setText("Add Item");
        Add_product_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_product_btnActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(similar_products));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout add_jpanelLayout = new javax.swing.GroupLayout(add_jpanel);
        add_jpanel.setLayout(add_jpanelLayout);
        add_jpanelLayout.setHorizontalGroup(
            add_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(add_jpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(add_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(7, 7, 7)
                .addGroup(add_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(add_jpanelLayout.createSequentialGroup()
                        .addComponent(product_id_tfield, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(price_jlabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(price_tfield, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(quantity_left_jlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(quantity_left_tfield, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(quantity_jlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(quantity_tfield, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Add_product_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(add_jpanelLayout.createSequentialGroup()
                        .addComponent(product_name_tfield, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        add_jpanelLayout.setVerticalGroup(
            add_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(add_jpanelLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(add_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, add_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(product_name_tfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)))
                .addGap(13, 13, 13)
                .addGroup(add_jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(product_id_tfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(price_jlabel)
                    .addComponent(price_tfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quantity_left_jlabel)
                    .addComponent(quantity_left_tfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quantity_jlabel)
                    .addComponent(quantity_tfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Add_product_btn))
                .addContainerGap())
        );

        proceed_btn.setText("Proceed");
        proceed_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proceed_btnActionPerformed(evt);
            }
        });

        jPanel1.setAlignmentY(0.0F);

        customer_name_label.setText("Customer's Name");

        jLabel4.setText("Mobile Number");

        mobile_tfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobile_tfieldActionPerformed(evt);
            }
        });

        jLabel5.setText("Email");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(customer_name_label, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(customers_name_tfield, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mobile_tfield, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(email_tfield, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customer_name_label)
                    .addComponent(customers_name_tfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(mobile_tfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(email_tfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Order Panel");
        jLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        back_to_dashboard_btn.setBackground(new java.awt.Color(255, 255, 255));
        back_to_dashboard_btn.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        back_to_dashboard_btn.setForeground(new java.awt.Color(0, 51, 204));
        back_to_dashboard_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ritesh/icons/back.jpg"))); // NOI18N
        back_to_dashboard_btn.setText("Back");
        back_to_dashboard_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_to_dashboard_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(proceed_btn)
                .addGap(121, 121, 121))
            .addGroup(layout.createSequentialGroup()
                .addGap(285, 285, 285)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(back_to_dashboard_btn)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(add_jpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(back_to_dashboard_btn))
                .addGap(23, 23, 23)
                .addComponent(add_jpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(proceed_btn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    
        private String pd_name=new String();
        private String pd_id=new String();
        private int qty=1;
        private int qty_left=0;
        private double pd_price=0.0;
        private double gross_price=0.0;

        public static String cstmr_name=null;
        public static String mob=null;
        public static String email=null;
        public static long order_id;
        
        ArrayList<String> similar_products_list =  new ArrayList<>();
        String[] similar_products=new String[10];
        public static ArrayList<Order> orderlist2 = new ArrayList<>();
    
    private void proceed_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proceed_btnActionPerformed
        
        cstmr_name=customers_name_tfield.getText();
        mob=mobile_tfield.getText();
        email=email_tfield.getText();
        
        try(Connection con = new DBConnection().getConnection()){
            Statement stmt = con.createStatement();
            ResultSet rs=null;
            rs=stmt.executeQuery("SELECT order_id FROM orders ORDER BY s_no DESC");
            if(rs.next()){
                order_id=Long.parseLong(rs.getString("order_id"))+1;
            }
            con.close();
        }catch(Exception e){
            System.err.println(e);
        }
        
        
        if(user_role.equals("user")){
            Invoice send_info =  new Invoice();
            DashBoard db_board=new DashBoard();
            db_board.update_users_sales_table();
            db_board.setVisible(true);
            send_info.setVisible(true);
            this.setVisible(false);
        }else if(user_role.equals("admin")){
            Invoice send_info =  new Invoice();
            send_info.setVisible(true);
        }
        
        
    }//GEN-LAST:event_proceed_btnActionPerformed

    private void mobile_tfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobile_tfieldActionPerformed
        
        mob=mobile_tfield.getText();
        
        try(Connection con = new DBConnection().getConnection()){
            Statement stmt = con.createStatement();
            ResultSet rs=null;
            rs=stmt.executeQuery("SELECT * FROM customers WHERE customer_mobile='"+mob+"'");
            if(rs.next()){
                customers_name_tfield.setText(rs.getString("customer_name"));
                email_tfield.setText(rs.getString("customer_email"));
            }else
            {
                JOptionPane.showMessageDialog(null,"New Customer Please Enter Name and Mobile number !!","New Customer !!",JOptionPane.INFORMATION_MESSAGE);
                customers_name_tfield.setText(null);
                email_tfield.setText(null);
            }
            con.close();
        }catch(Exception e){
            System.err.println(e);
        }
    }//GEN-LAST:event_mobile_tfieldActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        
        pd_name=jComboBox1.getSelectedItem().toString();
        if(jComboBox1.getSelectedItem().equals("Select an Item !!")){
            System.out.println("else is executed");
            product_id_tfield.setText(null);
            price_tfield.setText(null);
            quantity_left_tfield.setText(null);
            product_name_tfield.setText(null);
            
        }else{
            
            try(Connection con = new DBConnection().getConnection()){
                Statement stmt = con.createStatement();
                ResultSet rs=stmt.executeQuery("SELECT product_id,price,quantity FROM products WHERE product_name='"+pd_name+"'");
                if(rs.next()){
                    product_id_tfield.setText(rs.getString("product_id"));
                    price_tfield.setText(rs.getString("price"));
                    quantity_left_tfield.setText(rs.getString("quantity"));
                    pd_price=Double.parseDouble(rs.getString("price"));
                }
                con.close();
            }catch(Exception e){
                System.err.println(e);
            }
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void Add_product_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_product_btnActionPerformed
        
        if(product_id_tfield.getText()==null||quantity_left_tfield.getText()==null)
        {
            JOptionPane.showMessageDialog(null,"Empty fields detected !!","Empty fields !!",JOptionPane.WARNING_MESSAGE);
        }
        else{
            
            pd_id=product_id_tfield.getText();
            pd_price=Double.parseDouble(price_tfield.getText());
            qty=Integer.parseInt(quantity_tfield.getText());
            qty_left=Integer.parseInt(quantity_left_tfield.getText());
            gross_price=pd_price*qty;
            
            if(qty_left>0){
                Order order;
                order = new Order(pd_name,pd_id,pd_price,qty,gross_price);
                orderlist2.add(order);

                //addRowToJTable();
                //populate data into j table
                DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                model.addRow(new Object[]{pd_name,pd_id,+pd_price,qty,gross_price,"X"});
                    
               
                Action delete = new AbstractAction()
                {
                    @Override
                    public void actionPerformed(ActionEvent e)
                    {
                        JTable table = (JTable)e.getSource();
                        int modelRow = Integer.valueOf( e.getActionCommand() );
                            ((DefaultTableModel)table.getModel()).removeRow(modelRow);
                            orderlist2.remove(modelRow);
                    }
                };
 
                ButtonColumn buttonColumn = new ButtonColumn(jTable1, delete, 5);
                buttonColumn.setMnemonic(KeyEvent.VK_D);

                qty_left-=qty;

                try(Connection con = new DBConnection().getConnection()){
                    Statement stmt = con.createStatement();
                    stmt.executeUpdate("UPDATE products SET quantity='"+qty_left+"' WHERE product_name='"+pd_name+"'");
                    con.close();
                }catch(Exception e){
                    System.err.println(e);
                }
            }else
            {
                JOptionPane.showMessageDialog(null,"Product quantity left is zero, pls come later !!","Product not available now !!",JOptionPane.INFORMATION_MESSAGE);
                product_name_tfield.setText(null);
                product_id_tfield.setText(null);
                price_tfield.setText(null);
                quantity_left_tfield.setText(null);
                quantity_tfield.setText(null);
            }
        }

    }//GEN-LAST:event_Add_product_btnActionPerformed

    private void product_name_tfieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_product_name_tfieldKeyReleased
        
        similar_products_list.clear();
        pd_name=product_name_tfield.getText();
        if(product_name_tfield.getText().isEmpty()){
            System.out.println("product_name_tfield.getText().isEmpty()");
        }
        else{
            pd_name+="%";
            
            try(Connection con = new DBConnection().getConnection()){
                Statement stmt = con.createStatement();
                ResultSet rs=stmt.executeQuery("SELECT * FROM products WHERE product_name LIKE '"+pd_name+"'");
                if(rs.next()){
                    similar_products_list.add("Select an Item !!");
                    similar_products_list.add(rs.getString("product_name"));
                    while(rs.next()){
                        similar_products_list.add(rs.getString("product_name"));
                    }
                    con.close();
                }
            }catch(Exception e){
                System.err.println(e);
            }
        }
        String[] array = new String[similar_products_list.size()];
        for(int i=0;i<array.length;i++){
            array[i]=similar_products_list.get(i);
        }
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(array));
    }//GEN-LAST:event_product_name_tfieldKeyReleased

    private void back_to_dashboard_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_to_dashboard_btnActionPerformed
        
        if(user_role.equals("user")){
            new DashBoard().setVisible(true);
            this.setVisible(false);
        }else if(user_role.equals("admin")){
            new AdminJframe().setVisible(true);
            this.setVisible(false);
        }
        
    }//GEN-LAST:event_back_to_dashboard_btnActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TryingTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TryingTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TryingTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TryingTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TryingTable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_product_btn;
    private javax.swing.JPanel add_jpanel;
    private javax.swing.JButton back_to_dashboard_btn;
    private javax.swing.JLabel customer_name_label;
    private javax.swing.JTextField customers_name_tfield;
    private javax.swing.JTextField email_tfield;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField mobile_tfield;
    private javax.swing.JLabel price_jlabel;
    private javax.swing.JTextField price_tfield;
    private javax.swing.JButton proceed_btn;
    private javax.swing.JTextField product_id_tfield;
    private javax.swing.JTextField product_name_tfield;
    private javax.swing.JLabel quantity_jlabel;
    private javax.swing.JLabel quantity_left_jlabel;
    private javax.swing.JTextField quantity_left_tfield;
    private javax.swing.JTextField quantity_tfield;
    // End of variables declaration//GEN-END:variables

}
